# Site settings
title: graffen.dk - my home on the interwebs
email: jesper@graffen.dk
description: > # this means to ignore newlines until "baseurl:"
  Just a few interesting links and basic information.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://graffen.dk" # the base hostname & protocol for your site
twitter_username: graffen
github_username:  graffen

# Build settings
markdown: kramdown
